package com.pivotal.cloudfoundry.service.broker.wlsjms;

import java.util.Hashtable;

import javax.annotation.Resource;
import javax.management.MBeanServerConnection;
import javax.management.Notification;
import javax.management.NotificationListener;
import javax.management.ObjectName;
import javax.management.remote.JMXConnector;
import javax.management.remote.JMXConnectorFactory;
import javax.management.remote.JMXServiceURL;
import javax.naming.Context;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import weblogic.management.mbeanservers.domainruntime.DomainRuntimeServiceMBean;
import weblogic.management.runtime.DeploymentManagerMBean;

public class WlsJmsFunctions {

	// Domain Runtime MBean Server connection
	MBeanServerConnection connection;
	// Deployment Manager JMX proxy
	DeploymentManagerMBean deploymentManager;

	private static Logger LOG = LoggerFactory.getLogger(WlsJmsFunctions.class);
	
	public void createJmsModule(String modname) {

	}

	private void setUp() throws Exception {
		LOG.info("*** Setting up...");

		// Get connection to the Domain Runtime MBean Server.
		// For more information, see
		// "Make Remote Connections to an MBean Server"
		// in Developing Custom Management Utilities Using JMX for Oracle
		// WebLogic Server.
		connection = getDomainRuntimeJMXConnection();

		// Get DeploymentManager JMX proxy.
		// For more information, see Oracle WebLogic Server MBean Reference.
		DomainRuntimeServiceMBean svcBean = (DomainRuntimeServiceMBean) weblogic.management.jmx.MBeanServerInvocationHandler
				.newProxyInstance(connection, new ObjectName(
						DomainRuntimeServiceMBean.OBJECT_NAME));
		deploymentManager = svcBean.getDomainRuntime().getDeploymentManager();

		// Add a JMX notification listener that outputs the JMX notifications
		// generated during deployment operations.
		connection.addNotificationListener(new ObjectName(
				"com.bea:Name=DeploymentManager,Type=DeploymentManager"),
				new DeployListener(), null, null);
	}

	/*
	 * Demonstrates the notifications that are generated by WebLogic Server
	 * deployment operations.
	 */

	private class DeployListener implements NotificationListener {

		public void handleNotification(Notification notification,
				Object handback) {
			LOG.info(" Notification from DeploymentManagerMBean " + 
			"  notification type:  " + notification.getType());
			String userData = (String) notification.getUserData();
			LOG.info("  userData:  " + userData);
		}

	}

	private MBeanServerConnection getDomainRuntimeJMXConnection()
			throws Exception {

		JMXServiceURL serviceURL = new JMXServiceURL("t3", "localhost", 7001,
				"/jndi/weblogic.management.mbeanservers.domainruntime");

		Hashtable h = new Hashtable();
		h.put(Context.SECURITY_PRINCIPAL, "admin");
		h.put(Context.SECURITY_CREDENTIALS, "password");
		h.put(JMXConnectorFactory.PROTOCOL_PROVIDER_PACKAGES,
				"weblogic.management.remote");

		JMXConnector connector = JMXConnectorFactory.connect(serviceURL, h);
		MBeanServerConnection connection = connector.getMBeanServerConnection();
		return connection;
	}
}
